### PR TITLE
Copy using ZeroClipboard.

### PR DESCRIPTION
**Pull request by rgbkrk**
Incorporates ZeroClipboard for when a user clicks share.

### CODE REVIEW

**Comment by jdfreder** [comment]
You probably don't want to upload ZeroClipboard to your repo if you don't have to.  Try this CDN that hosts it:  
http://cdnjs.com/libraries/zeroclipboard

**Comment by rgbkrk** [comment]
Rebased to remove zeroclipboard's flash file and updated to use CDN.

**Comment by rgbkrk** [comment]
I think I'll bring in the History PR before this one and rebase to include zeroclipboard cleanly.

**Comment by rgbkrk** [comment]
Rebased.

**Comment by rgbkrk** [comment]
Thanks @jdfreder.

**Pull request merged**
