### PR TITLE
Rudimentary history push and pop

### PR DESCRIPTION
**Pull request by rgbkrk**
Alright @jdfreder, have a look here.

I've added the history stuff on, but I'm hesitant to have it change the kernel.

### CODE REVIEW

**Comment by jdfreder** [comment]
You don't want a kernel to start every time someone clicks share.  You should look at using something like history.js.  Here is a CDN that hosts it:  
http://cdnjs.com/libraries/historyjs

**Comment by rgbkrk** [comment]
Any idea what issues historyjs skirts by not using the HTML5 API?

**Comment by rgbkrk** [comment]
HistoryJS will actually break the way we're handling the params when in an HTML4 environment (since it falls back to #). Then again, old browsers don't handle websockets well either.

**Comment by rgbkrk** [comment]
Tried out HistoryJS for a bit. I'd like to see how this does without HistoryJS for a bit. If we switch over, that'll be a separate PR.

**Pull request merged**
